stages:
  - test

.variables_template: &variables_definition
  variables:
    BASE_NAME: "mapper.lv2"
    PKG_CONFIG_PATH: "/opt/lv2/lib/pkgconfig:/opt/${CI_BUILD_NAME}/lib/pkgconfig:/usr/lib/${CI_BUILD_NAME}/pkgconfig"

.common_template: &common_definition
  <<: *variables_definition
  stage: test 

.build_template: &build_definition
  <<: *common_definition
  script:
    - meson --cross-file "${CI_BUILD_NAME}" build
    - ninja -C build

.test_template: &test_definition
  <<: *common_definition
  script:
    - meson --cross-file "${CI_BUILD_NAME}" build
    - ninja -C build
    - cd build
    - meson test --verbose --wrap "${CI_BUILD_NAME}.wrap"

.universal_linux_template_stretch: &universal_linux_definition_stretch
  image: ventosus/universal-linux-gnu:stretch
  <<: *test_definition

.universal_linux_template_buster: &universal_linux_definition_buster
  image: ventosus/universal-linux-gnu:buster
  <<: *test_definition

.universal_linux_template_bullseye: &universal_linux_definition_bullseye
  image: ventosus/universal-linux-gnu:bullseye
  <<: *test_definition

.arm_linux_template_stretch: &arm_linux_definition_stretch
  image: ventosus/arm-linux-gnueabihf:stretch
  <<: *test_definition

.arm_linux_template_buster: &arm_linux_definition_buster
  image: ventosus/arm-linux-gnueabihf:buster
  <<: *test_definition

.arm_linux_template_bullseye: &arm_linux_definition_bullseye
  image: ventosus/arm-linux-gnueabihf:bullseye
  <<: *test_definition

.universal_w64_template: &universal_w64_definition
  image: ventosus/universal-w64-mingw32
  before_script:
    - ln -s /usr/i686-w64-mingw32/lib/libwinpthread-1.dll /opt/i686-w64-mingw32/lib/libwinpthread-1.dll
    - ln -s /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll /opt/x86_64-w64-mingw32/lib/libwinpthread-1.dll
  <<: *test_definition

.universal_apple_template: &universal_apple_definition
  image: ventosus/universal-apple-darwin
  <<: *build_definition

# building in docker
x86_64-linux-gnu-stretch:
  <<: *universal_linux_definition_stretch

x86_64-linux-gnu-buster:
  <<: *universal_linux_definition_buster

x86_64-linux-gnu-bullseye:
  <<: *universal_linux_definition_bullseye

i686-linux-gnu-stretch:
  <<: *universal_linux_definition_stretch

i686-linux-gnu-buster:
  <<: *universal_linux_definition_buster

i686-linux-gnu-bullseye:
  <<: *universal_linux_definition_bullseye

arm-linux-gnueabihf-stretch:
  <<: *arm_linux_definition_stretch

arm-linux-gnueabihf-buster:
  <<: *arm_linux_definition_buster

arm-linux-gnueabihf-bullseye:
  <<: *arm_linux_definition_bullseye

aarch64-linux-gnu-stretch:
  <<: *arm_linux_definition_stretch

aarch64-linux-gnu-buster:
  <<: *arm_linux_definition_buster

aarch64-linux-gnu-bullseye:
  <<: *arm_linux_definition_bullseye

x86_64-w64-mingw32:
  <<: *universal_w64_definition

i686-w64-mingw32:
  <<: *universal_w64_definition

universal-apple-darwin:
  <<: *universal_apple_definition
