stages:
  - build
  - deploy

.variables_template: &variables_definition
  variables:
    PKG_CONFIG_PATH: "/opt/lv2/lib/pkgconfig:/opt/${CI_BUILD_NAME}/lib/pkgconfig:/usr/lib/${CI_BUILD_NAME}/pkgconfig"
    BUILD_OPTS: "-Duse-fontconfig=disabled -Duse-qt4=false -Duse-qt5=false -Duse-gtk2=false -Duse-gtk3=false"

.common_template: &common_definition
  <<: *variables_definition
  stage: build
  artifacts:
    name: "${CI_PROJECT_NAME}-$(cat VERSION)-${CI_BUILD_NAME}"
    paths:
      - "${CI_PROJECT_NAME}-$(cat VERSION)/${CI_BUILD_NAME}/"

.build_template: &build_definition
  <<: *common_definition
  script:
    - meson --prefix="${CI_PROJECT_DIR}/${CI_PROJECT_NAME}-$(cat VERSION)/${CI_BUILD_NAME}" -Dlv2libdir="" --cross-file "${CI_BUILD_NAME}" ${BUILD_OPTS} build
    - ninja -C build
    - ninja -C build test
    - ninja -C build install

.universal_linux_template: &universal_linux_definition
  image: ventosus/universal-linux-gnu
  <<: *build_definition

.arm_linux_template: &arm_linux_definition
  image: ventosus/arm-linux-gnueabihf
  <<: *build_definition

.universal_w64_template: &universal_w64_definition
  image: ventosus/universal-w64-mingw32
  <<: *build_definition

.universal_apple_template: &universal_apple_definition
  image: ventosus/universal-apple-darwin
  <<: *build_definition

# building in docker
x86_64-linux-gnu:
  before_script:
    - apt-get install -y libjack-dev libglu1-mesa-dev libevdev-dev
  <<: *universal_linux_definition

i686-linux-gnu:
  before_script:
    - apt-get install -y libjack-dev:i386 libglu1-mesa-dev:i386 libevdev-dev:i386
  <<: *universal_linux_definition

arm-linux-gnueabihf:
  before_script:
    - apt-get install -y libjack-dev:armhf libglu1-mesa-dev:armhf libevdev-dev:armhf
  <<: *arm_linux_definition

aarch64-linux-gnu:
  before_script:
    - apt-get install -y libjack-dev:arm64 libglu1-mesa-dev:arm64 libevdev-dev:arm64
  <<: *arm_linux_definition

#x86_64-w64-mingw32:
#  <<: *universal_w64_definition
#
#i686-w64-mingw32:
#  <<: *universal_w64_definition
#
#universal-apple-darwin:
#  <<: *universal_apple_definition

pack:
  <<: *variables_definition
  stage: deploy
  script:
    - echo 'packing up...'
  artifacts:
    name: "${CI_PROJECT_NAME}-$(cat VERSION)"
    paths:
      - "${CI_PROJECT_NAME}-$(cat VERSION)/"
