language:
 - c
os:
 - linux
compiler:
 - gcc
 - clang
before_install:
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - iflin wget https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
 - iflin tar xzf v1.4.2.tar.gz
 - iflin sudo add-apt-repository -y ppa:andykimpe/cmake
 - iflin sudo apt-get -q update
install:
 - iflin pushd libuv-1.4.2 && iflin sh autogen.sh && iflin ./configure --prefix=/usr && iflin make && iflin sudo make install && iflin popd
 - iflin sudo apt-get install -y lv2core liblilv-dev libjack-dev libasound2-dev libportaudio-dev libelementary-dev cmake=2.8.12.2-3
before_script:
 - mkdir build && pushd build
 - iflin cmake -DCMAKE_C_FLAGS="-std=gnu99" -DBUILD_JACK=1 -DBUILD_UI=1 -DBUILD_PORTAUDIO=1 -DBUILD_TEST=1 -DBUILD_RTMIDI=0 ..
 - popd
script:
 - pushd build && make && sudo make install && popd
